-- Seed the Aspatuck club member directory from the 2026 v6 roster.
-- Multiple rows for the same person reflect distinct email contacts (e.g.
-- work + personal); the directory keys on email, not name.

insert into club_members (full_name, email) values
  ('Barry Altman',           'modularman@aol.com'),
  ('Sebastian Arango',       'sarango@gmail.com'),
  ('Sebastian Arango',       'SArango@kingstreet.com'),
  ('Bobby Bailin',           'bbbny@aol.com'),
  ('Robert Bellinger',       'rbellinger@asbcm.com'),
  ('David Bernfeld',         'bernfeld@gmail.com'),
  ('Jerry Blaine',           'jblaine@myldi.com'),
  ('Frank Brosens',          'FBrosens@taconiccap.com'),
  ('John Brosens',           'Jbrosens92@gmail.com'),
  ('John Brosens',           'Jbrosens@stolarcap.com'),
  ('Zachary Charles',        'Zacharycharles17@gmail.com'),
  ('Kevin Cino',             'cinobuilderscorp@gmail.com'),
  ('Eric Cohen',             'ericcohen@aol.com'),
  ('Barrie Covit',           'bcovit@stblaw.com'),
  ('Michael Dubb',           'Dubbland@aol.com'),
  ('Michael Dubb',           'Mdubb@Beechwoodhomes.com'),
  ('Marc Goodman',           'marcgoodman105@gmail.com'),
  ('Keith Feldman',          'Keithfeldman100@gmail.com'),
  ('James Fogarty',          'jfogarty@starwood.com'),
  ('Robert Forman',          'forman@formanshapiro.com'),
  ('Sam Frieder',            'Frieder@kohlberg.com'),
  ('Catherine Frey',         'catherine@f2pventures.com'),
  ('Gene Gilyutin',          'gene@hamptonestatesrealty.com'),
  ('Ike Harris',             'imh12652@gmail.com'),
  ('Marshall Heinberg',      'Marshall.heinberg40@gmail.com'),
  ('Matt Hoffman',           'matthew.hoffman@ubs.com'),
  ('Luke Hollman',           'lth22@cornell.edu'),
  ('David Kline',            'dkline@optonline.net'),
  ('David Kline',            'David.Kline@Charter.com'),
  ('Sylvia Kodsi',           'sylviakodsi@gmail.com'),
  ('Bob Kothari',            'akothari0511@gmail.com'),
  ('Jeffrey Lehman',         'jlehman@aramarcapital.com'),
  ('Jamie Lister',           'iamjlister@gmail.com'),
  ('Stacey Locker',          'staceylocker@gmail.com'),
  ('Stephan Mantelin',       'smantelin@gmail.com'),
  ('Sam Marzouk',            'sammarzouk@msn.com'),
  ('Gabriel Melamed',        'gabriel.melamed@gmail.com'),
  ('Chris Miller',           'cmnoblewines@gmail.com'),
  ('Dan Paltridge',          'djpaltridge@gmail.com'),
  ('Steve Paskiewicz',       'oldtennis22@aol.com'),
  ('Alex Penn',              'alexpenn02@gmail.com'),
  ('Larry Penn',             'penn@ellington.com'),
  ('Rob Pohly',              'rpohly@samlyncapital.com'),
  ('Evan Ratner',            'evan@chathamasset.com'),
  ('Todd Ross',              'tmr@onepointib.com'),
  ('Daniel Rudick',          'danielrudick@earthlink.net'),
  ('Scott Schwartzman',      'scott.schwartzman@sap.com'),
  ('Elliot Sealove',         'elliot@sealoveconsulting.com'),
  ('Maria Seidman',          'maria.seidman@gmail.com'),
  ('Maria Seidman',          'Maria@yapp.us'),
  ('Richie Silverstein',     'rdsdmd@optonline.net'),
  ('Joe Sokol',              'joseph@msokol.com'),
  ('Greg Spiegel',           'spiegggs@aol.com'),
  ('Mitchell Spiegel',       'bms16969@aol.com'),
  ('Mitchell Spiegel',       'mspiegel@evcmllc.com'),
  ('Robert Stillman',        'Robert.stillman@cbre.com'),
  ('Michael Thaler',         'michael.thaler@hubinternational.com'),
  ('Dan Tudor',              'danubius@aol.com'),
  ('Andrew Turtel',          'aturtelmd@gmail.com'),
  ('Pankaj Vasudev',         'pankajvasudev@gmail.com'),
  ('Nick Veronis',           'nick@icapitalnetwork.com'),
  ('Douglas Wendell',        'Wendellcustomhomes@hotmail.com'),
  ('Peter Worth, Jr',        'peterworthjr@gmail.com'),
  ('Daniel Zelenko',         'dzelenko@crowell.com'),
  ('Rodney Way',             'rodway71@icloud.com'),
  ('Mike Kosinski',          'Mkosinski123@gmail'),
  ('Adam Epstein',           'adam.epstein@ubs.com'),
  ('Jacqueline (Jacqui) Erani', 'Jacqueline.corba@gmail.com'),
  ('Robbie Erani',           'robbieerani@gmail.com'),
  ('Sharad Kohli',           'sharadkohli@gmail.com'),
  ('Larry Kramer',           'larry@kramertalent.com'),
  ('Ryan Lewis',             'rdlewis74@gmail.com'),
  ('Mark Malloy',            'malloy171@gmail.com'),
  ('Scott Meyers',           'sc_meyers@yahoo.com'),
  ('Glenn Nussdorf',         'nussdorf1@aol.com'),
  ('Greg Park',              'gregparkny@gmail.com'),
  ('Arthur Rentzler',        'arthur.rentzler@baruchmail.cuny.edu'),
  ('Brian Reiss',            'brianreiss07@gmail.com'),
  ('Peter Gruenberg',        'psg4@optonline.net')
on conflict (lower(email)) do nothing;
